name: Tests
run-name: Testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x  
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Display Python python-version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests with pytest and codecov
        run: |
          # stop the tests if there are erros in tests code
          pytest --cov=tests
          # if success
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{secrets.CODECOV_TOKEN}}